### ISSUE TITLE
Remove requirement for email address

### ISSUE THREAD

**Issue by edent** [openregister/registers-frontend#325]
As a user, I don't want to give you my email address in order to access Open Data.

### What did you do? (steps to reproduce)
I disagreed with the privacy policy, so I registered with a fake email address `_@example.com`
I also lied about not working for Government.

### What happened? (actual results)
I received an API key.  You sent email to someone who doesn't exist. Or to someone I wanted to annoy.

### What should have happened? (expected results)
Make the email address optional.  Clearly state that it is only needed if the user wants to be contacted for demographic research or updates.

**Comment by edent** [comment]
Being dealt with in #327

**Comment by injms** [comment]
I'm closing this issue because an email address is no longer required when accessing the API or downloading; and you can now [sign up for updates](https://www.registers.service.gov.uk/sign-up-for-updates) - which is the best way to get the latest GOV.UK Registers news... 💌
