### ISSUE TITLE
Fog gem message

### ISSUE THREAD

**Issue by fjavierm** [openregister/registers-frontend#46]
Do we need to take a look to this? I assume we are using the AWS part and obviously our Ruby version in bigger.

Post-install message from fog:

Thank you for installing fog!

IMPORTANT NOTICE:
If there's a metagem available for your cloud provider, e.g. `fog-aws`,
you should be using it instead of requiring the full fog collection to avoid
unnecessary dependencies.

'fog' should be required explicitly only if:
- The provider you use doesn't yet have a metagem available.
- You require Ruby 1.9.3 support.

**Comment by danmitchell-** [comment]
FYI https://github.com/denkGroot/Spina/commit/ebb9bc68282f6bb2d57a6bfc95bd33d432331974

**Comment by fjavierm** [comment]
Ok, questions answered :) Thanks @danmitchell-
