### ISSUE TITLE
Deployment fails to live

### ISSUE THREAD

**Issue by freesteph** [openregister/registers-frontend#667]
## Description
Building the latest `master` works fine on CI, and it also deploys to sandbox (i.e `cf push -f manifest-research.yml`) fine. But once the `master` branch is built on Travis, the deploy script takes over and [fails because it can't find the gems it just installed](https://travis-ci.org/openregister/registers-frontend/builds/648469883#L806).

I believe it's related to https://github.com/cloudfoundry/ruby-buildpack/issues/120 but would love to find a solution that does not involve downgrading our buildpack. 

Here's the full error:

```
-----> Creating runtime environment
/tmp/contents118876275/deps/0/bundler/gems/bundler-2.1.4/lib/bundler/spec_set.rb:86:in `block in materialize': Could not find rake-12.3.2 in any of the sources (Bundler::GemNotFound)
	from /tmp/contents118876275/deps/0/bundler/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `map!'
	from /tmp/contents118876275/deps/0/bundler/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `materialize'
	from /tmp/contents118876275/deps/0/bundler/gems/bundler-2.1.4/lib/bundler/definition.rb:170:in `specs'
	from /tmp/contents118876275/deps/0/bundler/gems/bundler-2.1.4/lib/bundler/definition.rb:237:in `specs_for'
	from /tmp/contents118876275/deps/0/bundler/gems/bundler-2.1.4/lib/bundler/definition.rb:226:in `requested_specs'
	from /tmp/contents118876275/deps/0/bundler/gems/bundler-2.1.4/lib/bundler/runtime.rb:101:in `block in definition_method'
	from /tmp/contents118876275/deps/0/bundler/gems/bundler-2.1.4/lib/bundler/runtime.rb:20:in `setup'
	from /tmp/contents118876275/deps/0/bundler/gems/bundler-2.1.4/lib/bundler.rb:149:in `setup'
	from /tmp/contents118876275/deps/0/bundler/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `block in <top (required)>'
	from /tmp/contents118876275/deps/0/bundler/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:136:in `with_level'
	from /tmp/contents118876275/deps/0/bundler/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:88:in `silence'
	from /tmp/contents118876275/deps/0/bundler/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `<top (required)>'
	from /tmp/contents118876275/deps/0/ruby/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /tmp/contents118876275/deps/0/ruby/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:92:in `require'
       **ERROR** Unable to write profile.d: Failed to run 'rake secret': exit status 1
```

**Comment by freesteph** [comment]
@rjbaker do you know if a Travis pipeline will automatically use the latest `ruby_buildpack` available? [The latest build of the master branch](https://travis-ci.org/github/openregister/registers-frontend/builds/661159236?utm_source=github_status&utm_medium=notification) was 8 days ago but it still used Buildpack 1.8.8 (see [the build log](https://api.travis-ci.org/v3/job/661159237/log.txt) search for "Buildpack"), which is a month old and as seen [multiple releases](https://github.com/cloudfoundry/ruby-buildpack/releases). Do you know why it didn't pick up the latest at the time? The [manifest file](https://github.com/openregister/registers-frontend/blob/master/manifest.yml#L4) doesn't seem to pin that version.

I hope this all makes sense, thanks a lot for the help.

**Comment by paroxp** [comment]
Buildpack versions are controlled by PaaS. Not all the releases may have been allowed in the platform.

You can run `cf buildpacks` to check what's the current buildpack PaaS will choose for your application. At the moment it's `v1.8.11`.

**Comment by paroxp** [comment]
Also to answer why it picked up `v1.8.8`  8 days ago, that's because PaaS just bumped the version on Monday (4 days ago):

https://github.com/alphagov/paas-cf/pull/2272/files#diff-f6a204290d8ed19c0db18abe20ac331bL321

**Comment by rjbaker** [comment]
As @paroxp said, `ruby_buildpack` will resolve to the buildpacks currently offered by the PaaS platform, these are updated from the Cloudfoundry upstream regularly. However if it's an urgent fix or you need some feature only offered in a particular Ruby version, you can point to the buildpack release directly i.e `- https://github.com/cloudfoundry/ruby-buildpack#v1.8.14`.

Bear in mind your app will be pinned to that version and won't receive regular updates as it currently does.

**Comment by freesteph** [comment]
@rjbaker @paroxp thanks a million! Very happy to report the [build is green again](https://travis-ci.org/github/openregister/registers-frontend/builds/664501634?utm_medium=notification&utm_source=github_status). Buildpack upgrade did it.
